name: Build Quote Application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Frontend Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: npm

      - name: Install
        run: npm ci

      - name: Test
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Packaging
        uses: actions/upload-artifact@v3
        with:
          name: quote-of-the-day
          path: dist/
